# name of produced library
LIB=libunic
# cflags needed for every build
CFLAGS ?= $(shell cat compile_flags.txt)
# linker flags needed for every build
LDFLAGS ?=
# source files that are dynamically generated 
GEN_SRC = src-gen/ucdb.c

# generate .d files
CFLAGS += -MMD
# cflags needed only for release builds
OPT_CFLAGS ?= -O3 -march=native -mtune=native -flto
OPT_CFLAGS += $(CFLAGS)

.PHONY: build codegen

build: out/$(LIB).so out/$(LIB).a


src-gen/ucdb.h src-gen/ucdb.c include/unic.h: codegen/*.py codegen/template/*
	cd codegen; python ./program.py
	mkdir -p src-gen
	cp codegen/out/unic.h include/
	cp codegen/out/ucdb.c codegen/out/ucdb.h src-gen/

codegen: src-gen/ucdb.c

# object files to generate
OBJECTS = $(patsubst src/%.c, out/%.o, $(wildcard src/*.c)) $(patsubst src-gen/%.c, out/%.o, $(GEN_SRC))
DEBUG_OBJECTS = $(patsubst %.o, %-dbg.o, $(OBJECTS))
TEST_OBJECTS = $(patsubst test/%.c, test-out/%.so, $(wildcard test/*.c))

out/$(LIB).so: $(OBJECTS)
	cc -shared $(OPT_CFLAGS) $^ -o $@
out/$(LIB)-dbg.so: $(DEBUG_OBJECTS)
	cc -shared -g $(CFLAGS) $^ -o $@
out/$(LIB).a: $(OBJECTS)
	ar rcs $@ $^

out/%.o: src-gen/%.c
	mkdir -p $(@D)
	cc -c $(OPT_CFLAGS) $< $(LDFLAGS) -o $@
out/%.o: src/%.c $(GEN_SRC)
	mkdir -p $(@D)
	cc -c $(OPT_CFLAGS) $< $(LDFLAGS) -o $@
out/%-dbg.o: src-gen/%.c
	mkdir -p $(@D)
	cc -c $(CFLAGS) $< $(LDFLAGS) -o $@
out/%-dbg.o: src/%.c $(GEN_SRC)
	mkdir -p $(@D)
	cc -c $(CFLAGS) $< $(LDFLAGS) -o $@

# .d files are generated by gcc to enable incremental builds
-include $(wildcard out/*.d)
-include $(wildcard test-out/*.d)

.PHONY: test --

ccheck/ccheck ccheck/integer-provider.so ccheck/interface.h:
	if [ ! -d ccheck ]; then git clone https://github.com/loglob/ccheck; fi
	make -C ccheck

test-out/%.so: test/%.c ccheck/interface.h
	mkdir -p $(@D)
	cc -shared $(CFLAGS) $< -o $@

test: ccheck/ccheck out/$(LIB)-dbg.so -- ccheck/integer-provider.so $(TEST_OBJECTS)
	if [ ! -d testdata ]; then git clone https://github.com/loglob/unic --branch testdata testdata; fi
	./$^

.PHONY: clean

clean:
	rm -fr ccheck out src-gen test-out testdata

doc: unic.dox include/unic.h include/u8text.h
	mkdir -p doc
	doxygen $<
